# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Loads App Store Connect API Key"
  lane :load_api_key do
    app_store_connect_api_key(
      key_id:    ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_filepath: ENV.fetch("APP_STORE_CONNECT_KEYFILE")
    )
  end

  desc "Bump build number to FASTLANE_BUILD_NUMBER"
  lane :increment_build do
    bump_number = ENV.fetch("FASTLANE_BUILD_NUMBER")
    increment_build_number(build_number: bump_number)
    git_add(path: "../*")
    git_commit(message: "chore: bump build number → #{bump_number}")
  end

  desc "Build the app"
  lane :build do
      puts ENV["FASTLANE_USER"]
    get_certificates(
      team_id:  ENV["FASTLANE_TEAM_ID"]
    )

    ENV['APP_IDENTIFIERS'].split(',').map(&:strip).each do |app_id|
      get_provisioning_profile(
        app_identifier: app_id,
        team_id: ENV["FASTLANE_TEAM_ID"]
      )
    end

    build_app(scheme: ENV.fetch("FASTLANE_IOS_SCHEME"))
  end

  desc "Deploy a new beta to TestFlight"
  lane :deploy_beta do
      load_api_key
      increment_build
    build
    upload_to_testflight(
      username: ENV["FASTLANE_USER"],
      app_identifier: ENV['APP_IDENTIFIERS'].split(',').first,
      skip_waiting_for_build_processing: true
    )
  end

end