name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'MORE-563*'

env:
  XCODE_VERSION: '14.2.0'
  JAVA_VERSION: '17'


jobs:
  build-shared:
    name: Build shared module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build shared
        run: ./gradlew shared:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: shared-module
          path: |
            shared/build

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: shared-module

      - name: Build Android
        run: ./gradlew androidApp:build androidApp:bundleDebug androidApp:bundleRelease androidApp:assembleRelease

      - name: Collect Artifacts
        run: |
          mkdir -p artifacts
          cp androidApp/build/outputs/apk/debug/androidApp-debug.apk artifacts/
          cp androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk artifacts/
          cp androidApp/build/outputs/bundle/debug/androidApp-debug.aab artifacts/
          cp androidApp/build/outputs/bundle/release/androidApp-release.aab artifacts/

      - name: Upload Release Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-release-bundle
          path: artifacts/*

  build-ios:
    name: Build Ios App
    runs-on: macos-latest
    if: false
    needs: build-shared
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MacOS
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}



